export const SERVICES_LIST_REQUEST = "SERVICES_LIST_REQUEST";
export const SERVICES_LIST_SUCCESS = "SERVICES_LIST_SUCCESS";
export const SERVICES_LIST_FAIL = "SERVICES_LIST_FAIL";

export const SERVICES_CREATE_REQUEST = "SERVICES_CREATE_REQUEST";
export const SERVICES_CREATE_SUCCESS = "SERVICES_CREATE_SUCCESS";
export const SERVICES_CREATE_FAIL = "SERVICES_CREATE_FAIL";

export const SERVICES_UPDATE_REQUEST = "SERVICES_UPDATE_REQUEST";
export const SERVICES_UPDATE_SUCCESS = "SERVICES_UPDATE_SUCCESS";
export const SERVICES_UPDATE_FAIL = "SERVICES_UPDATE_FAIL";

export const SERVICES_DELETE_REQUEST = "SERVICES_DELETE_REQUEST";
export const SERVICES_DELETE_SUCCESS = "SERVICES_DELETE_SUCCESS";
export const SERVICES_DELETE_FAIL = "SERVICES_DELETE_FAIL";
